# ===== Profil DEV : base de donnees H2 (en memoire) =====
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 : http://localhost:8085/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Schema recree a chaque demarrage + donnees de test (data.sql)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
