spring.application.name=ProductAPI
server.port=${PORT:8085}

# ===== Profil actif par defaut (on demarre en dev) =====
spring.profiles.active=dev

# ===== Configuration commune aux deux profils =====
spring.jpa.show-sql=true

# Securite (commune dev/prod)
spring.security.user.name=maryem
spring.security.user.password=1234
spring.security.user.roles=ADMIN
